### ISSUE TITLE
字型优化建议

### ISSUE THREAD

**Issue by GuuuWei** [Warren2060/Chill-Round#3]
聚害摇

![image](https://github.com/Warren2060/Chill-Round/assets/11283300/ba943c29-256d-453f-8924-a8f815fea3c3)

**Comment by Warren2060** [comment]
ok
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月23日(星期三) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Warren2060/Chill-Round] 字型优化建议 (Issue #3)





 
聚害摇

**Comment by Warren2060** [comment]
已更新。
