### ISSUE TITLE
在设置font-weight为700时，ChillRoundF字体中“欢”的左半边渲染错误

### ISSUE THREAD

**Issue by Allenyou1126** [Warren2060/Chill-Round#4]
如图，在Tailwind中，`font-bold`选择器会设置`font-weight: 700`，此时ChillRoundF字体渲染的“欢”字偏旁与其他“又”字旁的字明显不同，请问这是否是字体的问题？如果不是，请问有什么比较好的解决方案吗？

![image](https://github.com/Warren2060/ChillRound/assets/36348439/2685909f-257a-49de-a3cd-a32bb7ba3f0d)

**Comment by drtiand** [comment]
已经在另一个问题中修复

**Comment by Allenyou1126** [comment]
好的，非常感谢，如果作者接受了这个修改这个Issue就将Close

在 #5 中有同样问题

（这里Refer一下方便别人查看关系）

**Comment by Warren2060** [comment]
开始以为是使用路径导致的问题，检查文件可能是曲线方向不一致导致的，以修复。

**Comment by Allenyou1126** [comment]
问题已解决
