### ISSUE TITLE
字体font-weight较大，或手机端设置加粗时，字体显示异常

### ISSUE THREAD

**Issue by drtiand** [Warren2060/Chill-Round#5]
异常的字如下：
张欢纸纵绋fu统聍ning胀兖yan嗳ai宄gui怅悭惯枨脅xie蕴yun赟yun藴yun蝤qiu蝥mao瞀mao钕nv钺yue铙nao锃zeng锓qin锛ben镄fei镔bin鹂
有些生僻字后面带拼音了

**Comment by drtiand** [comment]
找到问题了，是字的不同笔画的方向不同，将出问题的笔画的方向切换就可以了。
出问题的字体更新如下：
货剂张欢纸纵绋统聍胀兖嗳宄怅悭惯枨脅蕴赟藴蝤蝥瞀钕钺铙锃锓锛镄镔鹂
另外给出一段测试的html代码
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>字体效果测试</title>
<style>
@font-face {
    font-family: '寒蝉全圆体';
    src: url('寒蝉全圆体.ttf');
    format('truetype');
}
 .try {
    font-family: "寒蝉全圆体" !important;
    speak: none;
    font-style: normal;
    font-weight: 600;
    font-size: 100px;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
 .icon-tree:after {content: '\33';}
</style>
</head>
<body>
<i class="try">张欢纸纵绋统聍胀兖嗳宄怅悭惯枨脅蕴赟藴蝤蝥瞀钕钺铙锃锓锛镄镔鹂货剂</i>
</body>
</html>
```
把这个html文件与字体文件放在一个位置，直接运行html就可以看到效果了。
另外，上传一下基于[v3.102](https://github.com/Warren2060/ChillRound/releases/tag/v3.102)修改好的字体。
[寒蝉全圆体v3.102-修复.zip](https://github.com/Warren2060/ChillRound/files/14981470/v3.102-.zip)

**Comment by drtiand** [comment]
新增修复的字体：
济觊绞
基于[v3.102](https://github.com/Warren2060/ChillRound/releases/tag/v3.102)修改好的字体文件
[寒蝉全圆体v3.102-修复v2.zip](https://github.com/Warren2060/ChillRound/files/15040902/v3.102-.v2.zip)

**Comment by Allenyou1126** [comment]
这个解决方案能够解决 #4 的问题

**Comment by Warren2060** [comment]
已修复这些曲线方向导致的问题。

**Comment by drtiand** [comment]
最新版本问题已经修复，感谢
